ceadoor/cea.ac.in

README.md
=> Fix for: Add travis-ci badge to README #2

src/about.html, src/administration.html, src/contact.html, src/sass/admin.scss, src/sass/navbar.scss
=> pages navbar final

src/sass/carousel.scss
=> Add overlay to carousel for better readability

src/sass/carousel.scss, src/sass/course-Overview.scss, src/studies/btech-computer-science-engg.html
=> fix carousel bg black shade

src/studies/btech-electronics-and-communication-engg.html, webpack.config.js
=> Added Electronics and Communication HTML File

package-lock.json, src/studies/btech-mechanical-engg.html, webpack.config.js
btech-mechanical-engg.html was created and webpack.config updated with corresponding filename
=> added requested page and updated webpack.config

src/cea-experience/stories.html, webpack.config.js
=> add stories page #96

src/administration.html, src/contact.html, src/sass/navbar.scss
=> fix navbar in administration and contact

src/studies/btech-electrical-and-electronics-engg.html, webpack.config.js
added btech-electrical-and-electronics-engg.html and updated webpack config with page information.
@abhijithvijayan please check.
=> Added BTech-EEE page

src/news-and-events.html
I don't know if you wanted me to also link this to any other pages.
If you do, I can do that.
=> Added a news and events page.

src/index.html
=> fix stats content

src/campus-life/clubs-at-cea.html, webpack.config.js
@abhijithvijayan - please review! 👍 
For issue #108
=> Created new clubs page

README.md
center aligned some part to make it look attractive
=> center aligned 

src/contact.html
=> little bit of fonts

src/about/our-commitment.html, webpack.config.js
=> Creating a commitment page #117

src/resources.html, webpack.config.js
@abhijithvijayan - please review 👍 
For issue #109
=> Added Resources Page

webpack.config.js
#120 - Changed filename from "faculty.html" to "about/faculty.html"
Should work fine now!
=> Issue-120 - Fixed webpackage.config.js

src/studies/departments.html, webpack.config.js
fix: Issue 165 - create a departments page
- added departments page with header, footer and title
- updated webpack config
=> fix: Issue 165 - create a departments page

src/campus-life/clubs-at-cea/pulse-cea.html, webpack.config.js
The Pull Request closes #161 issue.
Description:
Added pulse-cea.html file and changed webpack.config.js accordingly.
=> Create a page for club06

src/studies/university.html, webpack.config.js
Create university.html with header and footer. Add university.html to weback.config.js
=> Create university.html with header and footer

src/studies/universities/ktu.html, webpack.config.js
Fixes: https://github.com/ceadoor/cea.ac.in/issues/163
=> Create university01 page

src/studies.html, webpack.config.js
@abhijithvijayan please review
for issue #146
=> Added studies page

src/campus-life/clubs-at-cea/nss-cea.html, webpack.config.js
The Pull Request closes #160 issue.
Description:
Added nss-cea.html file and changed webpack.config.js accordingly.
=> Create a page for club05

package-lock.json, src/news-and-events/whats-going-on.html, src/studies/universities/cusat.html, webpack.config.js
=> Added Universities

src/campus-life/clubs-at-cea/ieee-sb-cea.html
=> create a page for club01

src/news-and-events/whats-coming-up.html
Tried to add the whats coming up page, with all the mentioned elements included.
=> added the whats coming up page

src/index.html, src/index.js, src/sass/carousel-navbar.scss, src/sass/main.scss
Closes and fixes #52 
I also improved student's carousel with some properties
=> #52 Add carousel buttons and improved student's carousel

src/contact.html, src/index.html, src/index.js, src/sass/navbar.scss
=> Revert "Home/navbar content & fixes"

package-lock.json, package.json
=> updated DevDependencies & fixed warnings

src/sass/components.scss, src/sass/course_activities.scss, src/sass/course_faculty.scss, src/sass/main.scss, src/studies/btech-computer-science-engg.html
=> Course page tabs updates 

webpack.config.js
=> changes to webpack config

CONTRIBUTING.md, package-lock.json, package.json, webpack.config.js
using terser for js and optimize-css-assets-webpack-plugin for css
=> minifying js/css files & modules update
